# Generated by Django 5.2.8 on 2025-12-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="city",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="search",
            name="genre",
            field=models.CharField(max_length=20),
        ),
    ]
