# Generated by Django 5.2.8 on 2025-12-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0002_alter_search_city_alter_search_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("venue", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("cityState", models.CharField(max_length=30)),
                ("dateTime", models.DateTimeField()),
                ("priceMin", models.DecimalField(decimal_places=2, max_digits=10)),
                ("priceMax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("url", models.URLField()),
                ("imgUrl", models.URLField()),
            ],
        ),
    ]
