# Generated by Django 5.2.8 on 2025-12-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0003_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="cityState",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="dateTime",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="imgUrl",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="priceMax",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="priceMin",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="url",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="venue",
        ),
    ]
