# Generated by Django 5.2.8 on 2025-12-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0004_remove_ticket_address_remove_ticket_citystate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cityState",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="imgUrl",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priceMax",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priceMin",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="time",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="venue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
