# Generated by Django 5.2.8 on 2025-12-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0005_ticket_address_ticket_citystate_ticket_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
